__author__ = 'Federico Vaggi'

from squared_loss_function import SquareLossFunction
from log_squared_loss_function import LogSquareLossFunction
from normalized_squared_loss_function import NormalizedSquareLossFunction

